version: 0.2
            
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Start runtime build...
    finally:
      - echo Finaly runtime build...
  pre_build:
    commands:
      - echo Start Pre build...
    finally:
      - echo Finaly Pre build...
  build:
    commands:
      - echo iniciando build
      - echo Entering build phase...
      - echo Build started on `date`   
      - mvn package shade:shade
      - aws cloudformation package --template-file template.yaml --s3-bucket bucketlambdasam --output-template template-api-test-lambda-export.yaml   
      - pwd    
    finally:
      - pwd
      #- aws cloudformation deploy --template-file template-api-test-lambda-export.yaml --stack-name -api-test-lambda --capabilities CAPABILITY_IAM
  post_build:
    commands:
      - echo Start Pos build...
    finally:
      - echo Finaly Pos build...
artifacts:
  files:
    - template-api-test-lambda-export.yaml