AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  ProjectId:
    Type: String
    Default: api-teste-lambida,
    Description: AWS Lambda projectID
    
Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.aws.codestar.projecttemplates.handler.HelloWorldHandler
      CodeUri: ./target/HelloWorld-1.0.jar
      Runtime: java8
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /java
            Method: get

  PostHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.aws.codestar.projecttemplates.handler.HelloWorldHandler
      CodeUri: ./target/HelloWorld-1.0.jar
      Runtime: java8
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
